# Generated by Django 4.2.7 on 2023-12-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_vidstream_duration_vidstream_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidstream',
            name='preview',
            field=models.FileField(null=True, upload_to='preview'),
        ),
        migrations.AlterField(
            model_name='vidstream',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vidstream',
            name='size',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
