# Generated by Django 4.2.7 on 2023-12-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_vidstream_preview_alter_vidstream_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidstream',
            name='duration',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vidstream',
            name='preview',
            field=models.FileField(default='', null=True, upload_to='preview'),
        ),
    ]
