# Generated by Django 4.2.7 on 2023-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_vidstream_duration_alter_vidstream_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidstream',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
