# Generated by Django 4.2.7 on 2023-12-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_vidstream_last_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidstream',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
