# Generated by Django 4.2.7 on 2023-12-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='content',
            field=models.ImageField(upload_to='Uploaded_photos', verbose_name='photos'),
        ),
    ]
