"""
Django settings for xxxworld project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from pickle import FALSE

from cv2 import FACE_RECOGNIZER_SF_FR_COSINE

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=#%a6e@3epebb=gi^qi0!45o9nq(p0l$0-%rhcb4(%crqb32t#'




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'skandlovu@gmail.com'

EMAIL_HOST_PASSWORD = '1020lethu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


LOGIN_URL= 'login'


LOGIN_REDIRECT_URL= '/'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"



CRISPY_TEMPLATE_PACK = 'bootstrap4'



DEFAULT_AUTO_FIELD= 'django.db.models.BigAutoField'
""""
PAYFAST_SETTINGS = {
    'merchant_id': 'your_merchant_id',
    'merchant_key': 'your_merchant_key',
    'testing': True,  # Set to False for live transactions
    'receiver_email': 'your_email@example.com'
}
"""""


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'photos',
    'videos',
    'profiles',
    'crispy_forms',
    'crispy_bootstrap4',
    'watchanalytics',
    'payfast',
    'stream',
    'django_q',
]

Q_CLUSTER = {
    'name': 'xxxworld',
    'workers': 4,
    'recycle': 500,
    'timeout': 60,  # Set the timeout to a value suitable for your task
    'retry': 600,   # Set the retry to a value larger than the timeout
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',
    'db_failures': 1000,
    'redis': {
        'host': 'localhost',
        'port': 6379,
        'db': 0,
        'password': 'your_password',
        'socket_timeout': 3,
        'socket_connect_timeout': 3,
        'max_connections': 20,
        'retry_on_timeout': True,
        'skip_full': True
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xxxworld.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR ,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xxxworld.wsgi.application'

ASGI_APPLICATION = 'stream.routing.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS= [BASE_DIR, 'static/']


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'



AWS_ACCESS_KEY_ID='AKIAY45EECJP3US32H56'
AWS_SECRET_ACCESS_KEY_ID='aYwStOoh+NWZ/6SdaXGCkVthnRGp1QLj+VOqziwf'
AWS_STORAGE_BUCKET_NAME='xxxworldmedia'
AWS_S3_SIGNATURE_NAME='s3v4'
AWS_S3_REGION_NAME='eu-central-1'
AWS_S3_FILE_OVERWRITE=False
AWS_DEFAULT_ACL=None
AWS_S3_VERITY=True
DEFAULT_FILE_STORAGE='storages.backends.s3boto3.S3Boto3Storage'
